### ISSUE TITLE
GitOps应用之CI/CD

### ISSUE THREAD

**Issue by xuanyuanaosheng** [xuanyuanaosheng/xuanyuanaosheng.github.io#12]
### 简介
GitOps 是一个操作框架，它将应用开发中的 DevOps 最佳实践，比如版本控制、协作、合规和 CI/CD，应用到基础设施自动化中。
GitOps需要的组件每个代码仓库软件有不同的方案。下面以Gitlab的技术栈为例，实践一下简单的CI/CD.

### 工具链路
1.   需要配置gitlab-runner并根据实际情况选择合适的executors.
2.   安装对应的gitlab-runner
3.   注册到gitlab
4.   在项目里面写``文件即可

### 具体案例
1.   基于配置文件的CD，在实际工作中可能遇到这样一种情况，一个配置文件需要其他团队进行修改，服务部署运行在`gitlab-runner` 所在的服务器节点上。
``` 
```

### 参考
1.  https://sean22492249.medium.com/gitlab-ci-cd-%E4%BB%8B%E7%B4%B9%E8%88%87-runner-%E7%9A%84%E6%9E%B6%E8%A8%AD-afdbde9f22aa
2.  https://docs.gitlab.com/runner/

**Comment by xuanyuanaosheng** [comment]
在 GitLab 中，CI/CD 是通过 `.gitlab-ci.yml` 文件配置的，该文件位于项目的根目录中。GitLab CI/CD 使用 YAML 语法来定义构建、测试和部署的流程。

### 1. `.gitlab-ci.yml` 文件基本结构

```yaml
stages:          # 定义阶段
  - build
  - test
  - deploy

build_job:      # 作业名称
  stage: build  # 指定作业所属的阶段
  script:       # 定义执行的脚本
    - echo "Building the application..."
    - make build

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - make test

deploy_job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - make deploy
```

### 2. 主要元素

#### 1. stages
定义 CI/CD 流程的各个阶段。每个阶段可以包含一个或多个作业。

```yaml
stages:
  - build
  - test
  - deploy
```

#### 2. jobs
作业是 CI/CD 流程的基本单位，定义了在 CI/CD 中执行的具体任务。

```yaml
build_job:      # 作业名称
  stage: build  # 指定作业所属的阶段
  script:       # 定义执行的脚本
    - echo "Building the application..."
```

#### 3. script
指定在作业中执行的命令或脚本。

```yaml
script:
  - echo "Running tests..."
  - make test
```

#### 4. image
指定运行作业所需的 Docker 镜像。

```yaml
image: ruby:2.6  # 使用 Ruby 2.6 镜像
```

#### 5. variables
定义环境变量，可以在作业中使用。

```yaml
variables:
  MY_ENV_VAR: "some_value"
```

#### 6. before_script 和 after_script
在所有作业之前或之后执行的命令。

```yaml
before_script:
  - echo "This runs before each job"

after_script:
  - echo "This runs after each job"
```

#### 7. only 和 except
控制作业在特定条件下是否运行。

```yaml
deploy_job:
  stage: deploy
  script:
    - echo "Deploying application..."
  only:
    - master  # 仅在 master 分支上运行
```

#### 8. cache
缓存编译产物以加快后续作业的速度。

```yaml
cache:
  paths:
    - node_modules/
```

#### 9. artifacts
保存作业的输出，以供后续作业使用。

```yaml
artifacts:
  paths:
    - build/
  expire_in: 1 week  # 指定保存时间
```

### 3. 示例 `.gitlab-ci.yml`

```yaml
image: ruby:2.6  # 使用 Ruby 2.6 镜像

stages:
  - build
  - test
  - deploy

before_script:
  - echo "Setting up environment"

build_job:
  stage: build
  script:
    - echo "Building the application..."
    - make build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - make test

deploy_job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - make deploy
  only:
    - master  # 仅在 master 分支上运行

after_script:
  - echo "Cleaning up..."
```

### 4. GitLab CI/CD 的执行流程

1. **触发**: 每次推送代码到 GitLab 时，GitLab CI/CD 会自动触发相应的流水线。
2. **构建阶段**: 首先执行 `build` 阶段的作业。
3. **测试阶段**: 当 `build` 阶段成功完成后，执行 `test` 阶段的作业。
4. **部署阶段**: 最后，根据条件执行 `deploy` 阶段的作业。

### 5. 总结

- GitLab CI/CD 是一种强大的自动化工具，可以通过 `.gitlab-ci.yml` 文件灵活配置。
- 了解各个部分的配置和使用可以帮助你构建高效的持续集成和持续部署流程。

**Comment by xuanyuanaosheng** [comment]
##  如何在K8S中使用GitLab 的 CI/CD （并未验证，需要进一步验证并更新文档）

在 Kubernetes (K8S) 中使用 GitLab 的 CI/CD (持续集成和持续交付) 是一种非常常见的方式来实现自动化的应用程序部署。GitLab CI/CD 可以通过 GitLab Runner 集成到 Kubernetes 中，通过 Pipelines 自动化应用构建、测试和部署。下面是如何在 Kubernetes 集群中配置和使用 GitLab CI/CD 的步骤。

### 总体流程：
1. **准备 GitLab Runner**：在 Kubernetes 集群中部署 GitLab Runner。
2. **配置 GitLab CI/CD**：配置 `.gitlab-ci.yml` 文件来定义 CI/CD Pipeline。
3. **通过 Helm、Kustomize 或其他方式进行部署**：使用 GitLab CI/CD 管理 Kubernetes 中的应用部署。

### 详细步骤：

---

## 1. 在 K8S 中部署 GitLab Runner

GitLab Runner 是 GitLab 的 CI/CD 工具，用于执行 Pipelines。你可以通过 Helm Chart 将 GitLab Runner 部署在 Kubernetes 中。

### 1.1. 添加 GitLab Helm Chart 仓库
确保已经在 Kubernetes 集群中安装了 Helm。然后添加 GitLab 的 Helm 仓库：

```bash
helm repo add gitlab https://charts.gitlab.io/
helm repo update
```

### 1.2. 安装 GitLab Runner

运行以下命令在 Kubernetes 中安装 GitLab Runner：

```bash
helm install --namespace gitlab-runner --create-namespace gitlab-runner gitlab/gitlab-runner
```

这将创建一个 `gitlab-runner` 命名空间并安装 GitLab Runner。你也可以自定义一些参数，例如 Runner 的配置和资源限制，具体可以参考 Helm Chart 的 [values.yaml](https://docs.gitlab.com/runner/install/kubernetes.html#install-gitlab-runner-using-helm) 文件。

### 1.3. 注册 GitLab Runner

安装完成后，你需要注册 GitLab Runner，使其与 GitLab 实例关联。获取注册 token 后，执行以下命令注册 Runner：

```bash
kubectl exec -it <gitlab-runner-pod> -- gitlab-runner register
```

提供 GitLab 服务器地址、Token 和其他相关信息。

---

## 2. 在 GitLab 中配置 CI/CD Pipeline

要在 GitLab 中启用 CI/CD 功能，你需要创建 `.gitlab-ci.yml` 文件，定义应用的 CI/CD 流程。GitLab 会自动检测此文件并启动 Pipeline。

### 2.1. 创建 `.gitlab-ci.yml` 文件

这个文件定义了所有 CI/CD Pipeline 的步骤，包括构建、测试和部署到 Kubernetes。下面是一个简单的 `.gitlab-ci.yml` 示例，它展示了如何将应用部署到 Kubernetes 中。

```yaml
stages:
  - build
  - test
  - deploy

variables:
  # K8S 的配置
  KUBERNETES_NAMESPACE: "my-namespace"
  KUBERNETES_SERVER: "https://<K8S_API_SERVER>"
  KUBERNETES_CA_CERT: "<CA_CERT>"
  KUBERNETES_TOKEN: "<K8S_TOKEN>"
  KUBERNETES_USER: "gitlab-ci"

before_script:
  - export KUBECONFIG=$CI_PROJECT_DIR/.kube/config
  - mkdir -p ~/.kube
  - echo "$KUBERNETES_CA_CERT" | base64 --decode > ~/.kube/ca.crt
  - echo "$KUBERNETES_CONFIG" > ~/.kube/config

build:
  stage: build
  script:
    - echo "Building the application"
    # 添加构建命令
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Running tests"
    # 添加测试命令

deploy:
  stage: deploy
  script:
    - echo "Deploying to Kubernetes"
    - kubectl apply -f k8s/deployment.yaml
  environment:
    name: production
    url: https://your-production-url.com
  only:
    - master
```

### 2.2. 环境变量解释：
- `KUBERNETES_NAMESPACE`: 指定要部署到的 Kubernetes 命名空间。
- `KUBERNETES_SERVER`: Kubernetes API 服务器地址。
- `KUBERNETES_CA_CERT`: Kubernetes 集群的 CA 证书。
- `KUBERNETES_TOKEN`: 用于认证 Kubernetes API 的 Token。

这些变量可以通过 GitLab 的 "CI/CD Settings" 页面配置成项目的环境变量，或者直接在 `.gitlab-ci.yml` 中指定。

### 2.3. 部署到 Kubernetes

在 `deploy` 阶段，可以使用 `kubectl` 命令将应用部署到 Kubernetes 集群。确保你已经为应用准备好了 Kubernetes 的配置文件（例如 `deployment.yaml`、`service.yaml` 等）。

---

## 3. 配置 Kubernetes 服务账户权限

GitLab Runner 需要访问 Kubernetes API 来进行部署操作，因此需要配置服务账户权限。

### 3.1. 创建 Kubernetes 服务账户

创建一个新的服务账户并绑定 `cluster-admin` 角色：

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci-service-account
  namespace: gitlab-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-ci-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab-ci-service-account
    namespace: gitlab-runner
```

执行以下命令将其应用到集群：

```bash
kubectl apply -f service-account.yaml
```

### 3.2. 获取服务账户的 Token

执行以下命令获取服务账户的 Token，以便 GitLab Runner 连接到 Kubernetes 集群：

```bash
kubectl -n gitlab-runner get secret $(kubectl -n gitlab-runner get sa/gitlab-ci-service-account -o jsonpath='{.secrets[0].name}') -o jsonpath='{.data.token}' | base64 --decode
```

将这个 Token 添加到 GitLab 项目的 CI/CD 环境变量中，用于认证。

---

## 4. 执行 GitLab CI/CD Pipeline

当你在 GitLab 项目中推送代码时，GitLab CI/CD 将自动执行你在 `.gitlab-ci.yml` 中定义的步骤。

1. **构建阶段**：编译应用。
2. **测试阶段**：运行测试。
3. **部署阶段**：通过 `kubectl apply` 将应用部署到 Kubernetes 集群。

你可以在 GitLab 的 CI/CD 页面上查看每个步骤的执行状态。

---

### 总结：

通过以上步骤，你可以在 Kubernetes 集群中部署 GitLab Runner，配置 CI/CD Pipeline，并将应用自动部署到 Kubernetes 集群。GitLab 的 CI/CD 与 Kubernetes 的紧密集成，使得应用的自动化交付更加高效，同时也简化了部署流程。
