### ISSUE TITLE
监控系统 -- Prometheus + Grafana 技术栈

### ISSUE THREAD

**Issue by xuanyuanaosheng** [xuanyuanaosheng/xuanyuanaosheng.github.io#27]
## 监控架构
监控系统采用 Thanos的架构。

**Comment by xuanyuanaosheng** [comment]
### 下一代监控系统
1.   https://github.com/VictoriaMetrics/VictoriaMetrics

**Comment by xuanyuanaosheng** [comment]
## VictoriaMetrics

### 集群架构

![image](https://github.com/user-attachments/assets/6ebb6ea5-24cc-4d47-9d61-18c98dd1c1dd)


### 采集插件
- https://docs.victoriametrics.com/vmagent/

![image](https://github.com/user-attachments/assets/0067d9aa-f354-409f-8a82-ef94cab69371)

**Comment by xuanyuanaosheng** [comment]
### 采集exporter
- https://github.com/albertodonato/query-exporter
-  https://github.com/louislam/uptime-kuma


### Grafana 插件
- https://grafana.com/grafana/plugins/agenty-flowcharting-panel/
   - https://play.grafana.org/d/Unu5JcjWk/flowcharting-index?orgId=1
   -  https://algenty.github.io/flowcharting-repository/STARTED.html
   
- https://grafana.com/grafana/plugins/andrewbmchugh-flow-panel/
- https://github.com/VolkovLabs/business-charts

### 报警规则
- https://samber.github.io/awesome-prometheus-alerts/rules#host-and-hardware

### Grafana Dashboard
- https://github.com/starsliao/Prometheus
- https://echarts.volkovlabs.io/d/pL5iH7FVk/home?from=now-6h&to=now&var-var=Sales&refresh=5s
- https://play.grafana.org/d/bdnahipisghdsa/getting-started-with-grafana-play?orgId=1&from=now-1h&to=now&timezone=browser
- https://echarts.volkovlabs.io/d/pL5iH7FVk/home?from=now-6h&to=now&var-var=Sales&refresh=5s&orgId=1&timezone=browser
- https://echarts.volkovlabs.io/d/edut6lsdkhiioc/business-text?from=now-6h&to=now&timezone=browser&orgId=1
- https://grafana-rngkvrfyhllkibec6k.grafana.aliyuncs.com/d/pL5iH7FVk/echart-demo?orgId=1
- https://grafana-rngkvrfyhllkibec6k.grafana.aliyuncs.com/d/iN7tThXVk/home?orgId=1
- https://demo.grafana.aliyuncs.com/d/15129219-k8s-node-overview/node-overview?orgId=1&refresh=1m&var-datasource=ARMS-OpenTelemetry-Demo_1277589232893727_805acb&var-node=10.0.0.180&var-clusterUid=15129219
- https://demo.grafana.aliyuncs.com/d/15129219-k8s-deploy/kubernetes-deployment?orgId=1&var-datasource=ARMS-OpenTelemetry-Demo_1277589232893727_805acb&var-kubeDatasource=&var-namespace=ack-onepilot&var-name=ack-onepilot-ack-onepilot&var-clusterUid=15129219
- https://grafana-rngkvrfyhllkibec6k.grafana.aliyuncs.com/d/iN7tThXVk/home?orgId=1

**Comment by xuanyuanaosheng** [comment]
### Kube-prometheus
1.  怎样增加Prometheus的配置？
     - 解决方案：https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md

2.   怎样增加K8S集群外部的监控？
```
在 Kubernetes 集群中使用 `kube-prometheus` 监控集群外部的资源时，可以使用 `ServiceMonitor` 资源来定义 Prometheus 的抓取目标。通常，监控 Kubernetes 外部的服务或资源需要使用外部的地址或端点。通过 `ServiceMonitor` 配置，可以让 Prometheus 访问和抓取这些外部服务的指标。

### 示例场景
假设我们要监控一个运行在 Kubernetes 集群外部的 HTTP 服务，该服务提供 Prometheus 格式的指标，并且我们能够从 Kubernetes 集群访问该服务的 URL，例如：`http://external-service.example.com/metrics`。

### 配置步骤

1. **创建一个 `Endpoints` 资源**：在 Kubernetes 集群中定义外部服务的抓取地址。
2. **创建一个 `ServiceMonitor` 资源**：配置外部服务的抓取端点。

### 具体示例

#### 1. 创建 `Endpoints` 资源

首先，在 Kubernetes 集群中创建一个 `Endpoints` 资源，表示外部的监控目标地址。

创建一个文件 `external-endpoints.yaml`：

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service
  namespace: monitoring
subsets:
  - addresses:
      - ip: "93.184.216.34"  # 此处替换为外部服务的 IP 地址，或使用 `hostname` 字段指定域名
    ports:
      - port: 80             # 服务的端口号
```

> **注意**：这里的 `ip` 可以是外部服务的 IP 地址，或者使用 `hostname` 来指定域名。如果外部服务使用域名，将 `ip` 替换为 `hostname`。

将此文件应用到 Kubernetes 集群：

```bash
kubectl apply -f external-endpoints.yaml
```

#### 2. 创建 `Service` 资源

为了让 `ServiceMonitor` 资源发现 `Endpoints`，需要创建一个关联的 `Service` 资源。

创建一个文件 `external-service.yaml`：

```yaml
apiVersion: v1
kind: Service
metadata:
  name: external-service
  namespace: monitoring
  labels:
    app: external-service
spec:
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None  # 使用 None 表示这是一个无头服务（headless service），用于和 `Endpoints` 关联
```

应用此文件：

```bash
kubectl apply -f external-service.yaml
```

#### 3. 创建 `ServiceMonitor` 资源

`ServiceMonitor` 用于定义 Prometheus 抓取外部服务的规则，包括抓取的路径、端口、时间间隔等。

创建 `ServiceMonitor` 文件 `external-servicemonitor.yaml`：

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-service-monitor
  namespace: monitoring
  labels:
    release: prometheus  # 与 Prometheus Operator 的 label 选择器匹配
spec:
  selector:
    matchLabels:
      app: external-service  # 匹配上面定义的 Service 的标签
  endpoints:
    - port: 80
      path: /metrics  # 目标服务提供的 Prometheus 格式的 metrics 路径
      interval: 30s   # 抓取间隔时间
```

应用 `ServiceMonitor` 文件：

```bash
kubectl apply -f external-servicemonitor.yaml
```

### 验证配置

1. 确保 Prometheus 配置已自动更新，并包含了新的 `ServiceMonitor` 抓取配置。
   - 可以通过访问 Prometheus 的 Web 界面（通常是 `http://<prometheus-ip>:9090`），然后在 **Targets** 页面（`Status -> Targets`）中查看是否能看到 `external-service`。

2. 如果配置正确，并且外部服务可以访问，你应该能够看到该外部服务的 `UP` 状态，并能抓取其指标数据。

### 其他注意事项

- **网络可达性**：确保 Prometheus Pod 能够访问外部服务的 IP 地址或域名。如果 Kubernetes 集群部署在内网中，而外部服务在公网上，可能需要配置网络规则或设置出口代理。
- **安全性**：如果外部服务需要认证（如 Basic Auth），可以在 `ServiceMonitor` 的 `endpoints` 中配置认证信息。或者考虑使用带认证的 `HTTPS` 请求。
 

### 总结

通过 `ServiceMonitor` 和 `Endpoints` 配置，Prometheus 可以使用 `kube-prometheus` 抓取 Kubernetes 集群外部的资源，实现跨集群或跨网络的监控。这种方式在监控外部依赖系统（如外部数据库、外部 API 服务等）时非常有用。

下面给出一个具体的例子：

![image](https://github.com/user-attachments/assets/82a95cf4-a0a5-429c-a769-3d28de9fbbb7)

```

3.   怎样在K8S集群中开启thanos-sidecar ？
```
要在 Kubernetes 集群中使用 `kube-prometheus` 开启 `thanos-sidecar`，并与集群外部的 `thanos-query` 一起构建 `Thanos` 架构，需要进行以下步骤。以下是完整的配置和步骤：

### 1. 配置 Thanos Sidecar 以连接 Prometheus

`thanos-sidecar` 会附加到 `kube-prometheus` 中的 `Prometheus` 实例，用于将 Prometheus 中的数据存储到长期存储中（如对象存储）并提供查询功能。

首先确保以下几点：
- `kube-prometheus` 已经正确安装并正在运行。
- `Prometheus` 实例已经在 `kube-prometheus` 中运行。

#### 配置 Prometheus StatefulSet 加入 Thanos Sidecar

以下是如何修改 Prometheus 配置，以便在 Prometheus 中运行 `thanos-sidecar`。

1. 在 `kube-prometheus` 中找到 `Prometheus` 的 StatefulSet，通常位于 `prometheus-prometheus.yaml` 文件中（取决于安装方式和命名空间）。
   
2. 添加 `thanos-sidecar` 容器到 Prometheus 的 StatefulSet 中，并配置 Thanos 所需的对象存储（如 S3、GCS、MinIO 等）：

   ```yaml
   apiVersion: monitoring.coreos.com/v1
   kind: Prometheus
   metadata:
     name: prometheus-k8s
     namespace: monitoring
   spec:
     replicas: 2
     containers:
       - name: thanos-sidecar
         image: thanosio/thanos:v0.24.0
         args:
           - sidecar
           - --tsdb.path=/prometheus
           - --prometheus.url=http://127.0.0.1:9090
           - --objstore.config-file=/etc/thanos/objstore.yml
           - --grpc-address=0.0.0.0:10901
           - --http-address=0.0.0.0:10902
         ports:
           - name: grpc
             containerPort: 10901
           - name: http
             containerPort: 10902
         volumeMounts:
           - name: prometheus-storage-volume
             mountPath: /prometheus
           - name: thanos-objstore-config
             mountPath: /etc/thanos
     volumes:
       - name: thanos-objstore-config
         configMap:
           name: thanos-objstore-config
   ```

   > 注意：
   - `--objstore.config-file=/etc/thanos/objstore.yml` 是指向对象存储配置文件的路径。
   - `prometheus.url` 指向 Prometheus 服务的本地地址。
   - `thanos-objstore-config` 是一个 ConfigMap，包含对象存储的配置信息。

3. 创建 `thanos-objstore-config` ConfigMap 文件，并包含对象存储配置（以 MinIO 为例）：

   ```yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: thanos-objstore-config
     namespace: monitoring
   data:
     objstore.yml: |
       type: s3
       config:
         bucket: "thanos-bucket"
         endpoint: "minio.example.com:9000"
         access_key: "<YOUR-ACCESS-KEY>"
         secret_key: "<YOUR-SECRET-KEY>"
         insecure: true
   ```

   应用 ConfigMap：

   ```bash
   kubectl apply -f thanos-objstore-config.yaml
   ```

### 2. 配置 Service 暴露 Thanos Sidecar gRPC 端口

为了让外部的 `thanos-query` 连接 `thanos-sidecar`，需要暴露 `thanos-sidecar` 的 gRPC 端口。

创建一个 Service 文件 `thanos-sidecar-service.yaml`：

```yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar-grpc
  namespace: monitoring
spec:
  selector:
    prometheus: prometheus-k8s
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
      protocol: TCP
  type: LoadBalancer
```

应用 Service：

```bash
kubectl apply -f thanos-sidecar-service.yaml
```

> 注意：如果您使用的是云服务（如 AWS、GCP），请确保 LoadBalancer 类型的服务可以通过外网访问，以便外部的 `thanos-query` 能够访问到 `thanos-sidecar` 的 gRPC 服务。

如果无法使用 LoadBalancer（例如在裸机或非托管 Kubernetes 环境中），可以使用 NodePort 暴露服务：

```yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar-grpc
  namespace: monitoring
spec:
  selector:
    prometheus: prometheus-k8s
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
      nodePort: 30001  # 指定 NodePort 范围内的端口号
      protocol: TCP
  type: NodePort
```

应用 Service：

```bash
kubectl apply -f thanos-sidecar-service.yaml
```

#### 获取 LoadBalancer 或 NodePort 的地址

- 如果使用 `LoadBalancer` 类型的 Service，请在 Kubernetes 中查看 `EXTERNAL-IP`：

  ```bash
  kubectl get svc thanos-sidecar-grpc -n monitoring
  ```

- 如果使用 `NodePort` 类型的 Service，请获取 Kubernetes 节点的 IP 地址，并使用 `NodePort` 暴露的端口。

### 3. 在虚拟机上配置 Thanos Query

在虚拟机上运行 `thanos-query` 容器或二进制文件，并配置指向 `thanos-sidecar` 的 gRPC 地址。


### 3. 在虚拟机上启动 Thanos Query 并进行验证

在虚拟机上运行 `thanos-query`，例如通过以下命令运行：

```bash
docker run -d --name thanos-query -p 9090:9090 thanosio/thanos:v0.24.0 \
  query --store=<THANOS_SIDECAR_GRPC_ADDRESS>:10901
```

这样，虚拟机上的 `thanos-query` 将会通过 gRPC 地址连接到 `thanos-sidecar` 并访问 Prometheus 数据。

### 4. 访问 Thanos Query Web 界面

在浏览器中访问 `http://<VIRTUAL_MACHINE_IP>:9090`，查看 `Thanos Query` 的 UI 界面，您可以在界面中查询跨集群的 Prometheus 数据。

### 总结

通过以上步骤，您已经成功地在 Kubernetes 集群中启用了 `thanos-sidecar`，并与外部的 `thanos-query` 进行集成，形成了一个 Thanos 架构。Thanos Query 可以通过 `thanos-sidecar` 抓取 Prometheus 中的指标数据，支持长期存储和高可用性监控。
```

**Comment by xuanyuanaosheng** [comment]
1.  How to get all label names?
    Link → https://mon-prom.bruce.me/api/v1/labels

2.  How to get all value for a label named 'job'?
     Link → https://mon-prom.bruce.me/api/v1/label/job/values

3.  You could also do it for another label which value is e.g. 'application_support'.
     Link → https://mon-prom.bruce.me/api/v1/label/application_support/values

4.   How to get all metric names?
     Link → https://mon-prom.bruce.me/api/v1/label/__name__/values

5.  How to use query to get all data rather than from Thanos which sometimes cannot show all data?
      For instance, you want to search all records which fit the condition: job="wmi_exporter". Then you could use the expression 'query?query=xxxx'.
      Link → https://mon-prom.bruce.me/api/v1/query?query={job=%22wmi_exporter%22}

6.  How to get all firing Prometheus alerts?
     Link → https://mon-am.bruce.me/api/v1/alerts

**Comment by xuanyuanaosheng** [comment]
### Alertmanager  API
```test_am_mail.sh
#!/bin/bash

set -x

CURRENT_DIR=/opt/scripts/bash/test_am_mail

current=$(date '+%Y-%m-%d %H:%M:%S')

alerts='[
  {
    "labels": {
       "alertname": "============== [ TEST Email ] ==============",
       "app_service": "monitor system",
       "severity": "TEST",
       "time_stamp": "'${current}'",
       "description": "This is a test email from monitor system to test whether the alert line is OK, Please ignore thia alert"
     }
  }
]'

curl -XPOST -d"$alerts" http://10.67.39.28:9093/api/v1/alerts

```

**Comment by xuanyuanaosheng** [comment]
### 扩展监控
1.   硬件监控： https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
2.   网络监控：https://www.librenms.org/
3.   存储监控：https://github.com/XoruX/stor2rrd

**Comment by xuanyuanaosheng** [comment]
###  常见问题处理
1.   K8S里面的prometheus 监控不同类型的服务使用的： Pod Monitor, Service Monitor and Scrape Config ：

        https://medium.com/@helia.barroso/a-guide-to-service-discovery-with-prometheus-operator-how-to-use-pod-monitor-service-monitor-6a7e4e27b303

2.   Prometheus High Availability with Thanos in Kubernetes：https://acagroup.be/en/blog/prometheus-high-availability-with-thanos-in-kubernetes/

3.  Elevating Observability: Unleashing the Power of kube-prometheus Stack with Thanos Sidecar：https://blog.devops.dev/elevating-observability-unleashing-the-power-of-kube-prometheus-stack-with-thanos-sidecar-9d0c159bef2e

4.  监控服务器上占用资源的TOP 10的进程：  https://github.com/ncabatoff/process-exporter/issues/273

5.  有一个是监控系统的TOP的内存以及CPU： https://github.com/deajan/node-exporter-textfile-collector-scripts/blob/instant_cpu_usage/instant_per_process_cpu_mem_usage.sh

6.  基于node_exporter的监控脚本集合Textfile Collector Example Scripts：https://github.com/deajan/node-exporter-textfile-collector-scripts

7.  监控合集：https://pdai.tech/md/devops/tool/tool-list-monitoring.html
8.  All in One：Prometheus 多实例数据统一管理最佳实践: https://developer.aliyun.com/article/1477990

**Comment by xuanyuanaosheng** [comment]
### 监控自动化流程

<img width="677" alt="image" src="https://github.com/user-attachments/assets/c09c49d5-8a8d-4f68-ab9a-87d9a3b14132">

**Comment by xuanyuanaosheng** [comment]
### Thanos监控多套K8S集群架构

![Image](https://github.com/user-attachments/assets/2fa3dc3f-bdc5-45d3-b6a8-43431558d2fe)

### 架构方案
- 当公司只有一套K8S环境，在一套 K8S集群中部署多个 `Prometheus`实例，采集K8S集群中的不同指标，进而部署整套`Thanos`方案(Thanos and Multiple Prometheus Instances in a Single K8s Cluster)
- 但是现实情况是一般公司有多套K8S环境，这种情况下，可以将监控集群单独部署在一套 K8S中，该集群需要部署整套Thanos架构，对于其他的 K8S集群，则只需要部署 `thanos-sidecar`即可。(Thanos and Multiple K8s Clusters Monitored by Prometheus)

主要包含两部分：

- 在每套K8S集群中通过`kube-prometheus-stack` 部署对应的监控系统
- 由于`kube-prometheus-stack`只包含`thanos-sidecar`组件，需要通过https://github.com/bitnami/charts/tree/main/bitnami/thanos部署Thanos的其他组件
- Bitnami Thanos项目除了query，启用Compactor, Ruler or Store component等需要配置对象存储


### K8S子集群相关配置：主要配置Thanos Sidecar

> Prometheus Thanos Sidecar
```
    thanos:
      version: v0.35.1

  prometheusSpec:
    externalLabels: 
      cluster: k8s-dev-001
      env: prod

## 第二层代理使用Ingress Nginx，同时Ingress可以使用其他的服务
  thanosIngress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
      nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/grpc-backend: 'true'
      nginx.ingress.kubernetes.io/protocol: h2c
      nginx.ingress.kubernetes.io/proxy-read-timeout: '160'
    enabled: true
    hosts:
      - thanos-sitb-sidecar.bruce.me
    labels: {}
    nodePort: 30901
    paths:
      - /
    servicePort: 10901
    tls:
      - hosts:
          - thanos-sitb-sidecar.bruce.me
        secretName: star-docker-tls
    ingressClassName: nginx
    pathType: Prefix
```

> Prometheus alertmanager  
```
  prometheusSpec:
    additionalAlertManagerConfigs:
      - scheme: https
        static_configs:
          - targets:
              - alertmanager.bruce.me

    hostAliases: 
      - hostnames:
          - alertmanager.bruce.me
        ip: 10.18.175.20               

```


### 可视化K8S集群配置：主要配置Thanos-query，域名指向第一层代理的Openresty的地址
```
  dnsDiscovery:
    enabled: false
    sidecarsNamespace: cattle-monitoring-system
    sidecarsService: rancher-monitoring-thanos-discovery
  dnsPolicy: ''
  enabled: true
  existingSDConfigmap: ''
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraFlags:
    - '--grpc-client-tls-secure'
    - '--grpc-client-tls-skip-verify'
    

  stores:
    - thanos-uat-sidecar.bruce.me:443
    - thanos-dev-sidecar.bruce.me:443
```


### 第一层代理配置：Openresty,域名指向：子K8S集群的Ingress nginx节点
```
server {
    listen 443 ssl http2;
    server_name thanos-uat-sidecar.bruce.me;
    access_log /logs/nginxlogs/thanos-uat-sidecar.bruce.me_access.log main;
    error_log /logs/nginxlogs/thanos-uat-sidecar.bruce.me_error.log debug;

    #ssl_certificate /usr/local/nginx/conf/ssl/bruce.me.cer;
    #ssl_certificate_key /usr/local/nginx/conf/ssl/bruce.me.key;
    #ssl_protocols     TLSv1.2 TLSv1.3;
    #ssl_ciphers     HIGH:!RC4:!MD5:!aNULL:!eNULL:!NULL:!DH:!EDH:!EXP:+MEDIUM;
    #ssl_prefer_server_ciphers       on;

    grpc_ssl_verify off;
    grpc_ssl_session_reuse on;

    http2_max_requests 1000;

    location / {


        grpc_pass grpcs://thanos-uat-sidecar.bruce.me:443;

        grpc_read_timeout 300s;
        grpc_send_timeout 300s;
    }
}

```

### kube-prometheus-stack 配置alertmanager的配置文件
```
## 方案一：直接修改alertmanager的配置文件

global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_from: am@alertmanager.bruce.me
  smtp_hello: bruce-alertmanager
  smtp_require_tls: false
  smtp_smarthost: smtp.bruce.me:25  
route:
  receiver: "email_test"
  group_by: ['alertname', 'cluster']
  routes:
  - receiver: "email_database"
    matchers:
    - cluster="k8s-uat-001"
  - receiver: "msteams-webhook"
    matchers:
    - cluster="k8s-ops-001"    
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
receivers:
  - name: "email_test"
    email_configs:
      - to: 'test@bruce.me'
        send_resolved: true
  - name: "email_database"
    email_configs:
      - to: 'uat@bruce.me'
        send_resolved: true        
  - name: "msteams-webhook"
    msteams_configs:
      - webhook_url: 'https://XXXX/IncomingWebhook/kqrAqPnk1'
        send_resolved: true        
templates:
  - /etc/alertmanager/config/*.tmpl
```

### 参考文档
- Deploying Thanos and Prometheus on a K8s Cluster：https://enix.io/en/blog/thanos-k8s/
- Thanos: Aggregating Multiple Prometheus Instances：https://enix.io/en/blog/thanos-prometheus/
- thanos部署：https://wghdr.top/?p=1070
- Prometheus high availability with Thanos：https://medium.com/@55_learning/prometheus-high-availability-with-thanos-caf00cfd3a7b
- Confusion in sidecar setup with ingress for external access：https://github.com/prometheus-community/helm-charts/issues/2968
- Elevating Observability: Unleashing the Power of kube-prometheus Stack with Thanos Sidecar: https://blog.devops.dev/elevating-observability-unleashing-the-power-of-kube-prometheus-stack-with-thanos-sidecar-9d0c159bef2e
- Installing Prometheus in Europe and United States using kube-prometheus-stack:https://github.com/vijaybiradar/kube-prometheus-Stack-with-Thanos-Sidecar
- Putting Thanos gRPC Endpoints Behind a K8s Ingress：https://wrossmann.medium.com/putting-thanos-grpc-endpoints-behind-a-k8s-ingress-a5e21c7d0d85
- Deployment — Monitoring with Prometheus & Thanos [Part 2/2]:https://medium.com/@dast04/full-installation-monitoring-with-prometheus-thanos-part-2-2-fe98fcdbe448
- prometheus-kube-prometheus-thanos-gateway ingress use the wrong serviceName: https://github.com/prometheus-community/helm-charts/issues/3650
-  报警聚合(kube-prometheus-stack配置使用外部Alertmanager): https://github.com/prometheus-community/helm-charts/issues/2799  
- [Upgrading kube-prometheus-stack via Helm to chart v56.2.1 fails on Grafana with Sensitive key error](https://stackoverflow.com/questions/77912105/upgrading-kube-prometheus-stack-via-helm-to-chart-v56-2-1-fails-on-grafana-with)： https://stackoverflow.com/questions/77912105/upgrading-kube-prometheus-stack-via-helm-to-chart-v56-2-1-fails-on-grafana-with
- [Feature] Per-Store TLS configuration in Thanos Query:  https://github.com/thanos-io/thanos/issues/977
- gRPC with nginx ingress 502/503/504 errors: https://github.com/kubernetes/ingress-nginx/issues/6273
- Unable to communicate with Sidecar behind the Nginx Ingress: https://github.com/thanos-io/thanos/issues/5432
- Thanos (Prometheus) Tutorial: Remote Read/Write - mTLS - Step-by-Step!: https://github.com/antonputra/tutorials/tree/main/lessons/163
- kube-prometheus-Stack-with-Thanos-Sidecar: https://github.com/vijaybiradar/kube-prometheus-Stack-with-Thanos-Sidecar
- Configuring Thanos Secure TLS Cross-Cluster Communication: https://thanos.io/tip/operating/cross-cluster-tls-communication.md/#client-clusters-sidecarcingressyaml
- Monitoring System: https://cloudentity.com/developers/deployment-and-operations/operations/monitoring/
- Thanos DNS Service Discovery: https://thanos.io/tip/thanos/service-discovery.md/#dns-service-discovery

**Comment by xuanyuanaosheng** [comment]
在 Kubernetes 中使用 **kube-prometheus-stack**（Prometheus Operator）监控集群外部服务时，可以通过以下方案实现自动化服务发现：

---

### 方案一：通过 **Kubernetes Service/Endpoints** 模拟内部服务
**原理**：手动或通过控制器创建 Kubernetes 的 `Service` 和 `Endpoints` 对象，指向外部服务的 IP 和端口，利用 Prometheus 原生的 Kubernetes 服务发现机制。

#### 实现步骤：
1. **创建 Service 和 Endpoints**  
   定义 `Service` 和 `Endpoints` 对象，将外部服务映射为 Kubernetes 资源：
   ```yaml
   # external-service.yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: external-service
     namespace: monitoring
     annotations:
       prometheus.io/scrape: "true"    # 告诉 Prometheus 抓取该服务
       prometheus.io/port: "9090"      # 指定监控端口
   spec:
     ports:
     - name: http
       port: 9090
       targetPort: 9090
   ---
   apiVersion: v1
   kind: Endpoints
   metadata:
     name: external-service
     namespace: monitoring
   subsets:
   - addresses:
     - ip: 10.1.2.3   # 外部服务的实际 IP
     ports:
     - name: http
       port: 9090
       protocol: TCP
   ```

2. **应用配置**  
   ```bash
   kubectl apply -f external-service.yaml
   ```

3. **验证发现结果**  
   Prometheus 会自动发现带有 `prometheus.io/scrape: "true"` 注解的 Service，并抓取对应的 Endpoints。

---

### 方案二：使用 **HTTP SD（动态服务发现）**
**原理**：部署一个自定义的 HTTP 服务，动态生成 Prometheus 兼容的目标列表，Prometheus 定期从该服务拉取目标信息。

#### 实现步骤：
1. **部署 HTTP SD 服务**  
   编写一个简单的 HTTP 服务，返回外部服务列表（JSON 格式）：
   ```python
   # http-sd-server.py
   from flask import Flask
   app = Flask(__name__)

   @app.route('/targets')
   def targets():
       return [
           {
               "targets": ["external-service-1:9090", "external-service-2:9090"],
               "labels": {"env": "prod"}
           }
       ]

   if __name__ == '__main__':
       app.run(host='0.0.0.0', port=8080)
   ```
   使用 Docker 部署该服务到 Kubernetes。

2. **配置 Prometheus 抓取规则**  
   在 `values.yaml` 中通过 `additionalScrapeConfigs` 添加 HTTP SD 配置：
   ```yaml
   prometheus:
     prometheusSpec:
       additionalScrapeConfigs:
         - job_name: 'external-http-sd'
           http_sd_configs:
             - url: 'http://http-sd-service.monitoring.svc.cluster.local:8080/targets'
   ```

3. **应用配置并验证**  
   更新 Helm Release 后，Prometheus 会自动从 HTTP 服务获取监控目标。

---

### 方案三：结合 **ExternalName Service 与 Relabeling**
**原理**：通过 `ExternalName` Service 将外部服务映射为 Kubernetes 内部 DNS，再利用 Prometheus 的 Relabeling 机制动态生成监控目标。

#### 实现步骤：
1. **创建 ExternalName Service**  
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: external-db
     namespace: monitoring
     annotations:
       prometheus.io/scrape: "true"
   spec:
     type: ExternalName
     externalName: external-db.example.com  # 外部服务的 DNS
     ports:
     - port: 3306
       targetPort: 3306
   ```

2. **配置 Prometheus Relabeling**  
   在 `values.yaml` 中通过 Relabeling 解析 DNS：
   ```yaml
   additionalScrapeConfigs:
     - job_name: 'external-db'
       static_configs:
         - targets: [external-db.monitoring.svc.cluster.local]
       relabel_configs:
         - source_labels: [__address__]
           target_label: __param_target
         - source_labels: [__param_target]
           target_label: instance
         - target_label: __address__
           replacement: blackbox-exporter:9115  # 通过 Blackbox Exporter 探测
   ```

---

### 方案四：使用 **Consul 服务发现**
**原理**：将外部服务注册到 Consul，Prometheus 通过 `consul_sd_config` 自动发现目标。

#### 实现步骤：
1. **部署 Consul 并注册外部服务**  
   通过 Consul API 或配置文件注册外部服务：
   ```json
   {
     "service": {
       "name": "external-service",
       "address": "10.1.2.3",
       "port": 9090
     }
   }
   ```

2. **配置 Prometheus 集成 Consul**  
   在 `values.yaml` 中添加 Consul 服务发现：
   ```yaml
   prometheus:
     prometheusSpec:
       additionalScrapeConfigs:
         - job_name: 'external-consul-sd'
           consul_sd_configs:
             - server: 'consul-server:8500'
               services: ['external-service']
   ```

---

### 方案五：**自定义 Operator 同步外部服务**
**原理**：开发一个 Kubernetes Operator，将外部服务信息同步为 Kubernetes 的 `Endpoints` 或自定义资源（CRD），Prometheus 自动发现这些资源。

#### 实现步骤：
1. **开发 Operator**  
   使用 Kubebuilder 或 Operator SDK 编写 Operator，监听外部服务变化并生成 `Endpoints`。

2. **配置 Prometheus 发现规则**  
   Operator 生成的 `Endpoints` 会自动被 Prometheus 的 Kubernetes SD 发现。

---

### 总结
| 方案                | 适用场景                          | 复杂度 | 动态性       |
|---------------------|---------------------------------|--------|-------------|
| Kubernetes Service/Endpoints | 外部服务较少且静态          | 低     | 低          |
| HTTP SD             | 外部服务动态变化，需自定义逻辑  | 中     | 高          |
| Consul              | 已有 Consul 基础设施           | 高     | 高          |
| 自定义 Operator      | 大规模外部服务，需深度集成      | 高     | 高          |

**推荐选择**：
- **少量静态服务**：直接使用 `Service/Endpoints` 方案。
- **动态外部服务**：选择 **HTTP SD** 或 **Consul**。
- **云环境服务**：结合云厂商的 SD 机制（如 AWS EC2 SD、Azure VM SD）。

**Comment by xuanyuanaosheng** [comment]
在Kubernetes中使用kube-prometheus-stack（Prometheus Operator）通过`file_sd_configs`实现监控目标自动发现的步骤如下：

### 1. **创建持久化存储卷（PVC）**
   用于存储自动发现的目标文件，确保数据持久化。
   ```yaml
   apiVersion: v1
   kind: PersistentVolumeClaim
   metadata:
     name: prometheus-file-sd-pvc
     namespace: monitoring
   spec:
     accessModes:
       - ReadWriteOnce
     resources:
       requests:
         storage: 1Gi
   ```

### 2. **配置Prometheus CRD**
   在Helm values.yaml中配置附加的存储卷和抓取规则：
   ```yaml
   prometheus:
     prometheusSpec:
       additionalScrapeConfigs:
         - job_name: 'file-sd-example'
           file_sd_configs:
             - files:
               - /etc/prometheus/file_sd/*.json
       volumes:
         - name: file-sd-volume
           persistentVolumeClaim:
             claimName: prometheus-file-sd-pvc
       volumeMounts:
         - name: file-sd-volume
           mountPath: /etc/prometheus/file_sd
   ```

### 3. **生成附加抓取配置的Secret**
   创建包含额外抓取配置的Secret：
   ```bash
   echo -e "- job_name: 'file-sd-example'\n  file_sd_configs:\n  - files:\n    - /etc/prometheus/file_sd/*.json" > prometheus-additional.yaml
   kubectl create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml -n monitoring
   ```

### 4. **部署CronJob生成目标文件**
   创建CronJob定期生成目标文件并写入PVC：
   ```yaml
   apiVersion: batch/v1
   kind: CronJob
   metadata:
     name: file-sd-updater
     namespace: monitoring
   spec:
     schedule: "*/5 * * * *"
     jobTemplate:
       spec:
         template:
           spec:
             containers:
             - name: updater
               image: alpine:latest
               command:
               - /bin/sh
               - -c
               - |
                 echo '[{"targets": ["external-service:9090"], "labels": {"env": "prod"}}]' > /mnt/targets.json
               volumeMounts:
               - name: file-sd-volume
                 mountPath: /mnt
             restartPolicy: OnFailure
             volumes:
             - name: file-sd-volume
               persistentVolumeClaim:
                 claimName: prometheus-file-sd-pvc
   ```

### 5. **应用配置并验证**
   - 更新Helm release：
     ```bash
     helm upgrade prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring -f values.yaml
     ```
   - 检查Prometheus目标页面，确认`file-sd-example`任务是否成功发现目标。

### 关键点说明：
- **持久化存储**：确保目标文件在Pod重启后不丢失。
- **文件格式**：目标文件需为JSON/YAML格式，符合Prometheus规范。
- **自动重载**：Prometheus会自动检测文件变化，无需重启。
- **权限管理**：确保CronJob有写权限，Prometheus有读权限。

此方案通过动态更新文件实现自动发现，适用于监控Kubernetes集群外部服务或需要灵活管理目标的场景。
