### ISSUE TITLE
ELK日志系统

### ISSUE THREAD

**Issue by xuanyuanaosheng** [xuanyuanaosheng/xuanyuanaosheng.github.io#29]
### 
日志系统在IT公司非常常见。

### 日志处理数据流
- 实时日志在Kibana做展示处理，一般保留一个月
- 日志文件进行归档处理，一般保留一年
<img width="1193" alt="企业微信截图_17273185114003" src="https://github.com/user-attachments/assets/82762504-5521-4031-8d64-5d17f5ca0c70">

### 搭建

**Comment by xuanyuanaosheng** [comment]
### 一些组件的配置

**Comment by xuanyuanaosheng** [comment]
### 常见问题的处理

**Comment by xuanyuanaosheng** [comment]
### ES集群管理工具
1.   桌面客户端：https://github.com/Bronya0/ES-King
2.   ES集群报警工具： https://github.com/johnsusek/praeco
3.   桌面客户端： https://github.com/geek-fun/dockit

**Comment by xuanyuanaosheng** [comment]
### 另一个例子
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /opt/hsis*/log/*.json.log
  fields:
    type: "hsos"
  ignore_older: 2h
  tags: ["json"]
  exclude_files: ['.gz$']

processors:
  - drop_fields:
      fields: ["ecs", "input.type", "log.offset", "version","agent"]

output.kafka:
  hosts: ["elkkafka01:9092","elkkafka02:9092","elkkafka03:9092"]
  topic: "logstash-%{[fields.type]}"
  username: filebeat
  password: ReOwchIg
  timeout: 5
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
```

```
input {
        kafka {
                bootstrap_servers => "elkkafka01:9092,elkkafka02:9092,elkkafka03:9092"
                security_protocol => "SASL_PLAINTEXT"
                sasl_mechanism => "PLAIN"
                sasl_jaas_config => "org.apache.kafka.common.security.plain.PlainLoginModule required username='logstash'  password='XXX';"
                topics_pattern => ["logstash-.*"]
                group_id => "logstash_uat"
                client_id => "logstash_uat"
                codec => "json"
                consumer_threads => 1
                decorate_events => true
                auto_offset_reset => "earliest"
        }
}

filter {
      if [fields][type] {
        mutate {
          add_field => { "type" => "%{[fields][type]}" }
          add_field => { "path" => "%{[log][file][path]}" }
        }
        mutate {
          remove_field => [ "[fields][type]","[log][file][path]" ]
        }
      }
      if "json" in [tags] {
          json {
                source => "message"
          }
      }
}

output {
        elasticsearch {
                hosts => [ "localhost" ]
                index => "logstash-%{type}-%{+YYYY.MM.dd}"
        }
}
```
