### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by xuanyuanaosheng** [xuanyuanaosheng/xuanyuanaosheng.github.io#50]

**Comment by xuanyuanaosheng** [comment]
Ansible 是一个强大的自动化工具，主要用于配置管理、应用部署、任务自动化等。以下是一些常见的 Ansible 使用技巧，可以帮助提高效率、简化代码、避免常见问题：

### 1. **使用 Ansible Vault 加密敏感数据**
   - Ansible Vault 用于加密敏感数据，如密码、API 密钥等。可以使用 `ansible-vault` 命令对文件进行加密和解密。
   - 加密文件：
     ```bash
     ansible-vault encrypt secret.yml
     ```
   - 在 Playbook 中引用加密文件：
     ```yaml
     - name: Example playbook
       vars_files:
         - vault_secret.yml
       tasks:
         ...
     ```
   - 这样可以确保敏感信息不暴露在代码库中，提高安全性。

### 2. **使用动态 Inventory**
   - 动态 Inventory 可以根据环境或其他条件自动生成主机清单（Inventory），特别适合云环境和容器化场景。
   - 可通过编写 Python 脚本或使用官方的动态插件（如 AWS、GCP 插件）来生成 Inventory 文件。
   - 使用动态 Inventory 文件：
     ```bash
     ansible-playbook -i dynamic_inventory.py playbook.yml
     ```
   - 这样可以根据实时状态管理主机，避免静态 Inventory 文件的维护成本。

### 3. **使用 Roles 组织 Playbook**
   - Roles 是 Ansible 组织任务、变量、模板等内容的一种方式，便于复用代码和管理大型项目。
   - 使用 Roles 可以将任务分成多个模块化的单元，有助于结构化管理，代码复用性更高。
   - 目录结构示例：
     ```yaml
     site.yml
     roles/
       web/
         tasks/
         handlers/
         templates/
         files/
         vars/
     ```
   - 在 Playbook 中使用 Role：
     ```yaml
     - hosts: webservers
       roles:
         - web
     ```

### 4. **使用 `ansible.cfg` 优化配置**
   - 可以在项目目录或用户主目录下创建 `ansible.cfg` 文件，定义全局的 Ansible 配置，例如 Inventory 路径、SSH 参数等。
   - 示例 `ansible.cfg` 配置文件：
     ```ini
     [defaults]
     inventory = ./hosts
     remote_user = ansible
     host_key_checking = False
     ```
   - 通过优化配置文件，可以减少重复配置，提高执行效率。

### 5. **使用条件判断 (`when`) 控制任务执行**
   - `when` 可以根据条件执行任务，避免不必要的任务执行。
   - 例如，仅在特定操作系统上安装软件：
     ```yaml
     - name: Install Apache on CentOS
       yum:
         name: httpd
         state: present
       when: ansible_os_family == "RedHat"
     ```

### 6. **使用 `with_items` 和 `loop` 实现循环**
   - 使用 `with_items` 和 `loop` 可以简化重复操作，减少代码量。
   - 示例：
     ```yaml
     - name: Install multiple packages
       apt:
         name: "{{ item }}"
         state: present
       loop:
         - git
         - curl
         - vim
     ```

### 7. **使用 `delegate_to` 实现远程任务代理**
   - `delegate_to` 可以将任务委托给特定的主机执行，常用于需要通过中转服务器执行任务的场景。
   - 示例：
     ```yaml
     - name: Run a task on a different host
       command: hostname
       delegate_to: "another_host"
     ```

### 8. **使用 Handlers 触发状态更改**
   - Handlers 用于在某些状态发生变化时执行操作（例如重启服务），可避免冗余操作。
   - 示例：
     ```yaml
     - name: Update web configuration
       template:
         src: web.conf.j2
         dest: /etc/nginx/nginx.conf
       notify: Restart nginx

     handlers:
       - name: Restart nginx
         service:
           name: nginx
           state: restarted
     ```

### 9. **使用 Tags 控制任务执行**
   - Tags 可以选择性地执行 Playbook 中的特定任务，非常适合测试或分步执行。
   - 示例：
     ```yaml
     - name: Install web server
       hosts: webservers
       tasks:
         - name: Install Nginx
           apt:
             name: nginx
           tags: nginx
     ```
   - 运行时指定 Tag：
     ```bash
     ansible
     ```
继续 Ansible 的技巧：

### 10. **使用 Jinja2 模板灵活处理文件内容**
   - Jinja2 模板用于生成动态配置文件、脚本等。通过变量、条件判断、循环等特性可以灵活地定义模板。
   - 创建一个模板文件 `nginx.conf.j2`：
     ```nginx
     server {
       listen {{ http_port }};
       server_name {{ domain_name }};

       location / {
         proxy_pass http://{{ backend_server }};
       }
     }
     ```
   - 在 Playbook 中使用模板：
     ```yaml
     - name: Configure Nginx
       template:
         src: templates/nginx.conf.j2
         dest: /etc/nginx/nginx.conf
       vars:
         http_port: 80
         domain_name: example.com
         backend_server: 127.0.0.1
     ```
   - 通过 Jinja2 模板可以在配置文件中灵活填充参数，避免硬编码。

### 11. **使用 `register` 捕获任务输出**
   - `register` 可用于存储任务的输出，便于后续任务使用。
   - 示例：获取远程主机的 IP 并在后续任务中使用。
     ```yaml
     - name: Get IP address
       command: hostname -I
       register: ip_output

     - name: Show IP
       debug:
         msg: "The IP address is {{ ip_output.stdout }}"
     ```

### 12. **使用 `block` 和 `rescue` 进行错误处理**
   - `block` 用于对任务进行分组，`rescue` 和 `always` 用于处理异常和资源释放。
   - 示例：执行一系列任务出错时尝试恢复。
     ```yaml
     - block:
         - name: Try to update a package
           apt:
             name: non_existing_package
             state: latest
       rescue:
         - name: Fallback task on failure
           debug:
             msg: "Failed to update package, performing fallback"
       always:
         - name: Clean up
           debug:
             msg: "This will always run"
     ```

### 13. **使用 `ansible-pull` 实现拉模式部署**
   - `ansible-pull` 支持通过 Git 仓库拉取 Playbook 并在客户端执行，适合集中化配置的自动更新。
   - 用法示例：
     ```bash
     ansible-pull -U https://github.com/username/repo.git playbook.yml
     ```
   - 适合用于客户端拉取配置进行自动化管理。

### 14. **使用 `async` 和 `poll` 实现异步任务**
   - `async` 和 `poll` 可使任务异步执行，适用于耗时操作。
   - 示例：启动异步任务并在后台执行。
     ```yaml
     - name: Long running task
       shell: /path/to/long_task.sh
       async: 300
       poll: 0

     - name: Wait for task completion
       async_status:
         jid: "{{ task_result.ansible_job_id }}"
       register: job_result
       until: job_result.finished
       retries: 5
       delay: 10
     ```

### 15. **编写模块自定义功能**
   - Ansible 提供了自定义模块功能，使用 Python 编写定制模块满足特定需求。
   - 模块结构示例：
     ```python
     # my_module.py
     from ansible.module_utils.basic import AnsibleModule

     def run_module():
         module = AnsibleModule(
             argument_spec=dict(
                 name=dict(type='str', required=True)
             )
         )
         result = dict(
             changed=False,
             message=f"Hello {module.params['name']}"
         )
         module.exit_json(**result)

     if __name__ == '__main__':
         run_module()
     ```
   - 通过自定义模块，可以轻松扩展 Ansible 功能。

### 16. **使用 `delegate_to` 和 `local_action`**
   - `delegate_to` 将任务委托给指定节点执行，适合跨主机的任务。`local_action` 用于在本地主机执行任务。
   - 示例：在本地执行命令并将结果应用到远程主机。
     ```yaml
     - name: Get local system info
       local_action: command uname -a
       register: local_uname

     - name: Show local info on remote host
       debug:
         msg: "Local system info: {{ local_uname.stdout }}"
     ```

### 17. **调试技巧：使用 `-vvv` 和 `debug`**
   - `-vvv` 提高输出详细程度，帮助定位问题。
   - 示例：调试变量值。
     ```yaml
     - name: Debug variable value
       debug:
         var: variable_name
     ```

### 18. **优化 Inventory 和分组**
   - 将主机按功能、环境进行分组管理。Inventory 示例：
     ```ini
     [web]
     web01 ansible_host=192.168.1.10
     web02 ansible_host=192.168.1.11

     [db]
     db01 ansible_host=192.168.1.20
     ```

### 19. **使用 `assert` 实现条件检查**
   - `assert` 用于条件检查，确保环境满足要求后再执行。
   - 示例：检查磁盘空间是否足够。
     ```yaml
     - name: Check available disk space
       assert:
         that:
           - disk_space > 1024
         msg: "Insufficient disk space!"
     ```

### 20. **测试 Playbook**
   - 在开发环境先测试 Playbook，确保不影响生产环境。
   - 可以使用 `--check` 进行 Dry Run 测试：
     ```bash
     ansible-playbook playbook.yml --check
     ```

**Comment by xuanyuanaosheng** [comment]
下面是一个简单的Ansible初始化例子：
```
- hosts: all
  remote_user: automate
  become: True
  become_user: root
  gather_facts: False
 
  tasks:
    - name: disable selinux
      shell: setenforce 0
      ignore_errors: True
 
    - name: disable selinux for /etc/selinux/config
      lineinfile:
        path: /etc/selinux/config
        regexp: ^SELINUX=.+
        line: SELINUX=disabled
 
    - name: disable firewalld
      system:
        name: firewalld
        state: stopped
        enabled: False
 
    - name: ip_tables module kernel modeule autostart
      lineinfile:
        path: /etc/modules-load.d/ip_tables.conf
        create: True
        insertafter: 'EOF'
        line: ip_tables
 
    - name: load ip_tables kernel module
      shell: modprobe ip_tables
 
    - name: install iscsi
      yum:
        name: iscsi-initiator-utils
        state: present
    - name: start iscsid service
      systemd:
        name: iscsid
        state: started
        enabled: True
```
